# Generated by Django 5.0.4 on 2024-05-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jobpost_description_jobpost_posted_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='jobName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
