# Generated by Django 5.0.6 on 2024-05-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_skills_jobpost_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='type',
            field=models.CharField(choices=[('FULL', 'Full Time'), ('PART', 'Part Time'), ('INTERN', 'Intern Ship')], default='FULL', max_length=100),
        ),
    ]
