# Generated by Django 5.0.6 on 2024-05-12 11:11

import uploadapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
                ('description', models.CharField(max_length=200, validators=[uploadapp.models.validate_char])),
            ],
        ),
        migrations.AlterField(
            model_name='uploads',
            name='description',
            field=models.CharField(max_length=200, validators=[uploadapp.models.validate_char]),
        ),
    ]
